src/Entity/HistoryLog.php
<?php

namespace App\Entity;

use App\Repository\HistoryLogRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HistoryLogRepository::class)]
class HistoryLog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $export_name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $export_date = null;

    #[ORM\Column(length: 255)]
    private ?string $user_name = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getExportName(): ?string
    {
        return $this->export_name;
    }

    public function setExportName(string $export_name): self
    {
        $this->export_name = $export_name;

        return $this;
    }

    public function getExportDate(): ?\DateTimeInterface
    {
        return $this->export_date;
    }

    public function setExportDate(\DateTimeInterface $export_date): self
    {
        $this->export_date = $export_date;

        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }
}

src/Form/HistoryLogType.php
<?php

namespace App\Form;

use App\Entity\HistoryLog;
use DateTime;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;



class HistoryLogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('export_name')
            ->add('export_date', DateTimeType::class,  ['widget' => 'single_text',])
            ->add('user_name')
            ->add('location');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => HistoryLog::class,
        ]);
    }
}

src/Controller/HistoryLogController.php
<?php

namespace App\Controller;

use App\Entity\HistoryLog;
use App\Form\HistoryLogType;
use App\Repository\HistoryLogRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;


#[Route('/history/log')]
class HistoryLogController extends AbstractController
{
    #[Route('/', name: 'app_history_log_index', methods: ['GET'])]
    public function index(Request $request,  HistoryLogRepository $historyLogRepository): Response
    {
        //$form_search = $this->createForm(LogSearchType::class, []);

        $form_search = $this->createFormBuilder()
            ->setMethod('GET')
            ->add(
                'export_name',
                ChoiceType::class,
                [
                    'choices'  => $historyLogRepository->getNames(),
                    'label' => false,

                ]
            )
            ->add(
                'date_from',
                DateType::class,
                [
                    'placeholder' => 'Select a value',
                    'widget' => 'single_text',
                    'label' => false,
                ]
            )
            ->add('date_to', DateType::class,  ['widget' => 'single_text',  'label' => false,])
            ->getForm();

        $form_search->handleRequest($request);

        if ($criteria = $form_search->getData()) {
            $data = $historyLogRepository->findByFilterCrit($criteria);
        } else {
            $data = $historyLogRepository->findAll();
        }
        return $this->renderForm('history_log/index.html.twig', [
            'history_logs' => $data, //findBy(['export_name'=>$request->get('export_name')]),
            'form_search' => $form_search,

        ]);
    }

    #[Route('/new', name: 'app_history_log_new', methods: ['GET', 'POST'])]
    public function new(Request $request, HistoryLogRepository $historyLogRepository): Response
    {
        $historyLog = new HistoryLog();
        $form = $this->createForm(HistoryLogType::class, $historyLog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $historyLogRepository->add($historyLog, true);

            return $this->redirectToRoute('app_history_log_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('history_log/new.html.twig', [
            'history_log' => $historyLog,
            'form' => $form,
        ]);
    }



    #[Route('/{id}', name: 'app_history_log_show', methods: ['GET'])]
    public function show(HistoryLog $historyLog): Response
    {
        return $this->render('history_log/show.html.twig', [
            'history_log' => $historyLog,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_history_log_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, HistoryLog $historyLog, HistoryLogRepository $historyLogRepository): Response
    {
        $form = $this->createForm(HistoryLogType::class, $historyLog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $historyLogRepository->add($historyLog, true);

            return $this->redirectToRoute('app_history_log_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('history_log/edit.html.twig', [
            'history_log' => $historyLog,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_history_log_delete', methods: ['POST'])]
    public function delete(Request $request, HistoryLog $historyLog, HistoryLogRepository $historyLogRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $historyLog->getId(), $request->request->get('_token'))) {
            $historyLogRepository->remove($historyLog, true);
        }

        return $this->redirectToRoute('app_history_log_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %} Zadanie
			{% endblock %}
		</title>
		<link
		rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	</head>
	<body>
		{% block body %}{% endblock %}

		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	</body>
</html>

templates/history_log/_delete_form.html.twig
<form method="post" action="{{ path('app_history_log_delete', {'id': history_log.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ history_log.id) }}">
	<button class="btn">Delete</button>
</form>

templates/history_log/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/history_log/_form_search.html.twig
{{ form_start(form_search) }}
{{ form_widget(form_search) }}

<button type="submit" class="btn btn-info">Zatwierdź</button>
<a class="btn btn-success" href="{{ path('app_history_log_index') }}">Pokaż wszystkie</a>
{{ form_end(form_search) }}

templates/history_log/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit HistoryLog{% endblock %}

{% block body %}
    <h1>Edit HistoryLog</h1>

    {{ include('history_log/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_history_log_index') }}">back to list</a>

    {{ include('history_log/_delete_form.html.twig') }}
{% endblock %}

templates/history_log/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HistoryLog index
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Raport</h1>
		<div class="row">
			<div class="col-md-4">
				{{ include('history_log/_form_search.html.twig', {'button_label': 'Zapisz'}) }}				
			</div>
			<div class="col-md-8">
				<table class="table table-bordererd">
					<thead>
						<tr>
							<th>Nazwa</th>
							<th>Data</th>
							<th>Godzina</th>
							<th>Użytkownik</th>
							<th>Lokal</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for history_log in history_logs %}
							<tr>
								<td>{{ history_log.exportName }}</td>
								<td>{{ history_log.exportDate ? history_log.exportDate|date('Y-m-d') : '' }}</td>
								<td>{{ history_log.exportDate ? history_log.exportDate|date('H:i') : '' }}</td>
								<td>{{ history_log.userName }}</td>
								<td>{{ history_log.location }}</td>
								<td>
									<a class="btn btn-info" href="{{ path('app_history_log_show', {'id': history_log.id}) }}">show</a>
									<a class="btn btn-default" href="{{ path('app_history_log_edit', {'id': history_log.id}) }}">edit</a>
								</td>
							</tr>
						{% else %}
							<tr>
								<td colspan="6">no records found</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				<a class="btn btn-success" href="{{ path('app_history_log_new') }}">Dodaj nowy</a>
			</div>

		</div>
	</div>
{% endblock %}

templates/history_log/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New HistoryLog{% endblock %}

{% block body %}
    <h1>Create new HistoryLog</h1>

    {{ include('history_log/_form.html.twig') }}

    <a href="{{ path('app_history_log_index') }}">back to list</a>
{% endblock %}

templates/history_log/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}HistoryLog{% endblock %}

{% block body %}
    <h1>HistoryLog</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ history_log.id }}</td>
            </tr>
            <tr>
                <th>Export_name</th>
                <td>{{ history_log.exportName }}</td>
            </tr>
            <tr>
                <th>Export_date</th>
                <td>{{ history_log.exportDate ? history_log.exportDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>User_name</th>
                <td>{{ history_log.userName }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ history_log.location }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_history_log_index') }}">back to list</a>

    <a href="{{ path('app_history_log_edit', {'id': history_log.id}) }}">edit</a>

    {{ include('history_log/_delete_form.html.twig') }}
{% endblock %}